# Version: 20251015
# Image name: quay.io/opencv-ci/opencv-ubuntu-24.04

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    software-properties-common \
    curl \
    zip \
    unzip \
    wget \
    rsync \
    mc \
    nano \
    time \
    git \
    file

RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    cmake \
    build-essential \
    ccache \
    ninja-build \
    ant \
    ant-optional \
    default-jdk \
    python3-dev \
    python3-setuptools \
    python3-pip \
    zlib1g-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff5-dev \
    libopenjp2-7-dev \
    libavif-dev \
    libjxl-dev \
    libopenexr-dev \
    libgtk-3-dev \
    libgtk-4-dev \
    libcamera-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libavdevice-dev \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    libopenni2-dev \
    libaravis-dev \
    libdc1394-dev \
    libgphoto2-dev \
    hdf5-tools \
    libhdf5-dev \
    liblept5 \
    libgdal-dev \
    libgoogle-glog-dev \
    libarmadillo-dev \
    libeigen3-dev \
    libsuitesparse-dev \
    liblapacke-dev \
    libopenblas-dev \
    libeigen3-dev \
    libglfw3-dev \
    libceres-dev \
    lcov \
    xvfb \
    pkg-config

RUN python3 -m pip install --break-system-packages \
    numpy \
    pylint \
    requests \
    cairosvg && \
    pip cache purge

# Self-hosted runner UID is 1000

USER ubuntu

RUN \
  mkdir $HOME/opencv $HOME/opencv_contrib $HOME/build && \
  git config --global --add safe.directory "*" && \
  git config --global user.email "opencv.ci" && \
  git config --global user.name "opencv.ci" && \
  git config --global pull.rebase false

CMD bash
