name: Update DNN models
description: Update OpenCV extra DNN models cache

inputs:
  dnn-models:
    required: true
  target-branch-name:
    required: true

runs:
  using: composite
  steps:
    - name: Extra DNN models update
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        TARGET_BRANCH_NAME='${{ inputs.target-branch-name }}'
        LATEST_SAVED_HASH=$(cat $DNN_MODELS/dnn/latest-hash-${TARGET_BRANCH_NAME}.txt)
        LATEST_HASH=$(sha256sum opencv_extra/testdata/dnn/download_models.py | awk '{print $1}')

        if [[ $LATEST_HASH == $LATEST_SAVED_HASH ]]; then
          echo "DNN models are up to date"
          echo "OPENCV_DNN_TEST_DATA_PATH=$DNN_MODELS" >> $GITHUB_ENV
        else
          echo "Updating DNN models list"
          echo "OPENCV_DNN_TEST_DATA_PATH=${{ github.workspace }}/new-dnn-models" >> $GITHUB_ENV && OPENCV_DNN_TEST_DATA_PATH="${{ github.workspace }}/new-dnn-models"
          mkdir -p "$OPENCV_DNN_TEST_DATA_PATH"
          rsync -a --exclude=download_models.py $DNN_MODELS/* $OPENCV_DNN_TEST_DATA_PATH
          cp opencv_extra/testdata/dnn/download_models.py $OPENCV_DNN_TEST_DATA_PATH/dnn
          cd $OPENCV_DNN_TEST_DATA_PATH/dnn && python3 download_models.py
        fi
