# Version: 20240117
# Image name: quay.io/opencv-ci/opencv-ubuntu-22.04-riscv-071

FROM ubuntu:22.04 AS builder

ARG TOOLCHAIN_BRANCH=xuantie-gnu-toolchain
ARG TOOLCHAIN_COMMIT=7b294fcd5dbb6b8c2966941146a6b89ef0b5d3a1 # 2.8.0 + fix

RUN apt update && apt install -y \
    cmake \
    ccache \
    ninja-build \
    git \
    autoconf \
    automake \
    autotools-dev \
    curl \
    python3 \
    python3-pip \
    libmpc-dev \
    libmpfr-dev \
    libgmp-dev \
    gawk \
    build-essential \
    bison \
    flex \
    texinfo \
    gperf \
    libtool \
    patchutils \
    bc \
    zlib1g-dev \
    libexpat-dev \
    libglib2.0-dev

RUN git clone \
      -b ${TOOLCHAIN_BRANCH} \
      --recurse-submodules \
      --shallow-submodules \
      https://github.com/T-head-Semi/xuantie-gnu-toolchain.git

WORKDIR xuantie-gnu-toolchain

RUN git checkout ${TOOLCHAIN_COMMIT} --recurse-submodules

RUN ./configure --enable-linux --prefix=/opt/riscv
RUN make -j8 linux
RUN make -j8 build-qemu

#====================================================================

FROM ubuntu:22.04
COPY --from=builder /opt/riscv /opt/riscv

ENV PATH=/opt/riscv/bin:${PATH}
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    software-properties-common \
    cmake \
    ccache \
    ninja-build \
    python3 \
    rsync

RUN \
  add-apt-repository ppa:git-core/ppa && \
  apt update && apt install -y \
    git

RUN \
  mkdir -p /home/ci/opencv /home/ci/opencv_contrib /home/ci/build /home/ci/scripts && \
  git config --global --add safe.directory "*" && \
  git config --global user.email "opencv.ci" && \
  git config --global user.name "opencv.ci" && \
  git config --global pull.rebase false

COPY scripts/warnings-handling.py /home/ci/scripts/warnings-handling.py

WORKDIR /home/ci

CMD bash
