name: OCV WinPack:5.0.0 W10-ARM64

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/OCV-WinPack-5.0.0-W10-ARM64.yaml'
  workflow_dispatch:

concurrency:
  group: OCV-WinPack-5.0.0-W10-ARM64-${{ github.ref }}
  cancel-in-progress: true

env:
  BRANCH_NAME: 5.0.0

jobs:
  Build:
    runs-on: windows-arm64
    defaults:
      run:
        shell: bash
    env:
      EXTRA_CMAKE_OPTIONS: >-
        -A ARM64
        -DBUILD_SHARED_LIBS=ON
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_TESTS=OFF
        -DBUILD_PERF_TESTS=OFF
        -DINSTALL_CREATE_DISTRIB=ON
        -DINSTALL_PDB=ON
        -DINSTALL_PDB_COMPONENT_EXCLUDE_FROM_ALL=OFF
        -DOPENCV_GENERATE_SETUPVARS=ON
        -DBUILD_opencv_java=OFF
        -DBUILD_opencv_python2=OFF
        -DOPENCV_PYTHON_INSTALL_PATH=python
        -DBUILD_EXAMPLES=OFF
        -DBUILD_DOCS=OFF
        -DWITH_FFMPEG=OFF
        -DWITH_OPENCL=OFF
        -DWITH_OPENMP=OFF
        -DCPU_BASELINE=NEON
        -DCPU_DISPATCH=NEON
        -DCMAKE_SYSTEM_PROCESSOR=arm64
        -DOPENCV_WORKAROUND_CMAKE_20989=ON
        -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install

    steps:
    - name: Clean
      run: rm -rf "${{ github.workspace }}"/* "${{ github.workspace }}"/install

    - name: Clone opencv
      run: |
        cd "${{ github.workspace }}"
        git clone --single-branch --depth 1 --branch ${{ env.BRANCH_NAME }} https://github.com/opencv/opencv.git

    - name: Configure OpenCV
      run: |
        mkdir "${{ github.workspace }}/build" && cd "${{ github.workspace }}/build"
        cmake -G "Visual Studio 17 2022" ${{ env.EXTRA_CMAKE_OPTIONS }} "${{ github.workspace }}/opencv"

    - name: Build and install OpenCV
      run: |
        cd "${{ github.workspace }}/build"
        cmake --build . --config Release --target install -- /maxcpucount /consoleloggerparameters:NoSummary 2>&1 | tee build-log.txt

    - name: Warnings check
      continue-on-error: true
      run: python3 ./scripts/warnings-handling.py "${{ github.workspace }}/build/build-log.txt"

    - name: Pack WinPack installer (cpp + python)
      run: |
        mkdir "${{ github.workspace }}/artifacts"
        cd "${{ github.workspace }}/install"
        7z a -bd -sfx -y -mx7 ../artifacts/opencv-5.0.0-windows-arm64.exe ./

    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenCV-5.0.0-Windows-ARM64
        path: ${{ github.workspace }}/artifacts/opencv-5.0.0-windows-arm64.exe
